version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
