version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: mydb

  api:
    build:
      context: ./api
    ports:
      - "3008:3008"
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  auth_service:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: mydb
      POSTGRES_PORT: 5432
    build:
      context: ./authService
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  parser:
    build:
      context: ./parser
    ports:
      - "5000:5000"
    volumes:
      - ./parser:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - api
      - auth_service

volumes:
  postgres-data:
